# Generated by Django 5.0 on 2023-12-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_2',
            name='icons',
            field=models.ImageField(blank=True, upload_to='home_2/icons/'),
        ),
    ]
