# Generated by Django 5.0 on 2023-12-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Full_width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='full_width/image')),
                ('slide', models.ImageField(blank=True, upload_to='full_width/slide')),
                ('low_title', models.CharField(blank=True, max_length=255)),
                ('low_about', models.CharField(blank=True, max_length=255)),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='full_width/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('time', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Full_width',
                'verbose_name_plural': 'Full_widths',
            },
        ),
        migrations.CreateModel(
            name='Grid_Left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='grid_left/image')),
                ('slide', models.ImageField(blank=True, upload_to='grid_left/slide')),
                ('low_title', models.CharField(blank=True, max_length=255)),
                ('low_about', models.CharField(blank=True, max_length=255)),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='grid_left/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('time', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Grid_left',
                'verbose_name_plural': 'Grid_lefts',
            },
        ),
        migrations.CreateModel(
            name='List_sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='list-sidebar/image')),
                ('slide', models.ImageField(blank=True, upload_to='list-sidebar/slide')),
                ('low_title', models.CharField(blank=True, max_length=255)),
                ('low_about', models.CharField(blank=True, max_length=255)),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='list-sidebar/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('time', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'List-sidebar',
                'verbose_name_plural': 'List-sidebars',
            },
        ),
    ]
