# Generated by Django 5.0 on 2023-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='contact_us/image')),
                ('photo_1', models.ImageField(blank=True, upload_to='contact_us/image')),
                ('slide', models.ImageField(blank=True, upload_to='contact_us/slide')),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='contact_us/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('time', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact_us',
            },
        ),
    ]
