# Generated by Django 5.0 on 2023-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='gallery_left/image')),
                ('slide', models.ImageField(blank=True, upload_to='gallery_left/slide')),
                ('low_title', models.CharField(blank=True, max_length=255)),
                ('low_about', models.CharField(blank=True, max_length=255)),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='gallery_left/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('time', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Gallery_left',
                'verbose_name_plural': 'Gallery_lefts',
            },
        ),
        migrations.CreateModel(
            name='Sticky_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='sticky_left/image')),
                ('slide', models.ImageField(blank=True, upload_to='sticky_left/slide')),
                ('low_title', models.CharField(blank=True, max_length=255)),
                ('low_about', models.CharField(blank=True, max_length=255)),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='sticky_left/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('time', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Sticky_left',
                'verbose_name_plural': 'Sticky_lefts',
            },
        ),
        migrations.CreateModel(
            name='Tab_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='tab_left/image')),
                ('photo_1', models.ImageField(blank=True, upload_to='tab_left/image')),
                ('slide', models.ImageField(blank=True, upload_to='tab_left/slide')),
                ('low_title', models.CharField(blank=True, max_length=255)),
                ('low_about', models.CharField(blank=True, max_length=255)),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='tab_left/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('time', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Tab_left',
                'verbose_name_plural': 'Tab_lefts',
            },
        ),
    ]
